apiVersion: apps/v1
kind: Deployment
metadata:
  name: huego-deployment
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: huego
  template:
    metadata:
      labels:
        app: huego
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: huego-container
        image: ghcr.io/dme86/huego:0.1.0@sha256:10034796e35a248941e3d83eee8b48fd1d9114824f9749f679717f63561c1167 # arm64
        ports:
        - containerPort: 8000
        env:
        - name: HUE_BRIDGE_IP
          valueFrom:
            secretKeyRef:
              name: huego-secrets
              key: HUE_BRIDGE_IP
        - name: HUE_API_KEY
          valueFrom:
            secretKeyRef:
              name: huego-secrets
              key: HUE_API_KEY
        - name: SENSOR_ROOM_MAPPING
          valueFrom:
            secretKeyRef:
              name: huego-mapping-secret
              key: SENSOR_ROOM_MAPPING
---
apiVersion: v1
kind: Service
metadata:
  name: huego-service
  namespace: monitoring
spec:
  selector:
    app: huego
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

