apiVersion: apps/v1
kind: Deployment
metadata:
  name: huego-deployment
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: huego
  template:
    metadata:
      labels:
        app: huego
    spec:
      containers:
      - name: huego-container
        image: ghcr.io/dme86/huego@sha256:f473a4c8ace8023cab8c8bda242aeba501f7bb6a9b4a08aaf28b851b6f75d91b ## arm64
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: huego-service
  namespace: monitoring
spec:
  selector:
    app: huego
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

