name: Build and Push Multi-Arch Docker Image to GitHub Container Registry

on:
  push:
    tags:
      - '*' # Trigger only when a new tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --allow-insecure-entitlement security.insecure

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build and Push Docker image with both latest and tag
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
          -t ghcr.io/${{ github.repository }}:latest \
          --push .

